### ISSUE TITLE
fuel sometimes does not update  when hitting tfm plus f

### ISSUE THREAD

**Issue by marrie** [jfayre/talking-flight-monitor#108]
**Describe the bug**
when checking fuel, sometimes fuel won't update when I see how much is being used. I can get around this by checking my fuel page under fs actions. I notice this happens at random so I don't have an exact use case as to when this will happen.
**To Reproduce**
1. load into the 777 in my case F model. I've seen this in the default model as well.
2. fuel up to anything you like.
3. go through the check lists as normal
4. notice that when taking off and flying fuel won't update with the right tfm plus f, it even shows the wrong value. Example, mine shows about 320 thousand pounds when I put about 130 thousand so pounds  in there. I can't remember now. It has been staying there ever since this flight.

**Expected behavior**
I should see fuel go down, not stay the same.
**additional information
 - OS: [e.g. Windows 10]Windows 10 21H1 (x64) build 19043.1110
 - TFM version:  17.4 but I've seen this in 17.5
 - Flight simulator in use:  p3d version 4
- specific aircraft in use: boeing 777 F

**Additional context**
Add any other context about the problem here. What other add-ons were you running at the time, etc.
here is my fuel page as of now.

          FUEL          
 TOTAL LBS     GW/  MTOW
1: 127579       639.2/766.8
 LEVEL       TOCG    ZFW
2: 39.8%       28.2%  318.3
            FUEL DENSITY
3: <LONG RANGE         6.24
         PLAN FUEL (LBS)
4: <MED RANGE           N/A
                        
5: <SHORT RANGE            
                        
6: <RETURN                 
                        
 Here is what tfm shows.
total fuel: 320825.6 pounds. 47890.0 gallons. Total fuel flow: 20335

 if I check the fuel a few minutes later via the fuel page the number will drop. In the time it took me to write this report I have now dropped to 1: 126812       639.2/766.8 according to my fuel page but my tfm tanks show as max which is wrong.

**Comment by ajborka** [comment]
What version of FSUIPC do you have installed, and do you have FSUIPC 7 installed as well?

**Comment by ajborka** [comment]
Tested this with PMDG 77F, P3D 5.0, FSUIPC 6.1.4, and TFM alpha 17.5 source build. Everything works as expected.

**Comment by marrie** [comment]
I do not have FSUIPC 7 installed. I have version 6.13 according to the changes file in the zip. I’m in the middle of a long haul or something, so updating right now will not be possible, not without breakage.

**Comment by marrie** [comment]
This is random, so it will brake when ever it feels like it. It worked on my circle flight yesterday, but failed when I was going from vrmm  to omdb. Now I’m going from kind to egss and have according to my fuel page on the pmdg itself 1: 109716       639.2/766.8 but tfm srtill shows the same numbers I put in the  bug report, in fact my tanks show as full, all of them.

**Comment by ajborka** [comment]
Is this a result of using the FSUIPC autosave scenerio state feature? If so, TFM is only reading the last known state of the offsets. You would need to address the issue with FSUIPC in that case.

**Comment by marrie** [comment]
No, it is not. This also happened on a fresh flight, that is, this morning. Or at least, it should not be because of FSUIPC. I would not even know how to troubleshoot that. My copy is registered, the other person who is not having the issue has the free copy.

**Comment by ajborka** [comment]
This is either an FSUIPC problem or a PMDG thing. PMDG mentions in their instructional meterial that FSUIPC doesn't receive any values until the aircraft is fully powered up. In the event the APU shows 0 fuel burn, it is because the aircraft is now powered up completely. Lately though, we haven't been seeing this problem, so we are treating it as a PMDG/FSUIPC fix.
