### ISSUE TITLE
tfm not responding

### ISSUE THREAD

**Issue by BviPilots** [jfayre/talking-flight-monitor#111]
hi everhone. so randomly my tfm and even p3d will say not responding. after like 1 minute it comes back out of being locked and starts working again. I grabbed a line from the log and hopefully maybe i could get some feedback on this if its tfm or p3d or fsuipc. I was told to report it so here is the code.
2021/08/28 16:43:55.563 - tfm.TFMMainForm.TimerMain_Tick - High priority instruments failed to read: FSUIPC Error #9: FSUIPC_ERR_NOTOPEN. The connection to FSUIPC is not open.

**Comment by ajborka** [comment]
This no longer freezes. In the event it does, some other application is causing the problem. Users have reported fsuipc autosave or fsairlines client autosave can lock up things for a short time.
