### ISSUE TITLE
feature request: aircraft dialogue reads aircraft speed

### ISSUE THREAD

**Issue by blindflightsimmer** [jfayre/talking-flight-monitor#113]
If this can be pulled, aircraft dialogue with P would read airborn aircraft's indicated airspeed and groundspeed, useful for vatsim and spacing purposes

**Comment by ajborka** [comment]
Can you give a case where ] S, A, H, V, and M wont work for spacing and Vatsim?

**Comment by blindflightsimmer** [comment]
HI. This was referencing the speed of other aircraft, not the speed of your aircraft. For example yesterday, I get a traffic alert, use the right bracket P aircraft dialogue and see there’s an aircraft one mile away and below me, but I do not know his speed. Vpilot with the .aircraft command can show the other aircraft’s position, their altitude for example as TFM’s right bracket p already does, but also their speed. In this case the idea was to add to TFM’s dialogue so you can easily find it quickly, you can adjust accordingly. So, let’s say the guy ahead of me was at 200 kts, well then I can slow to 180 knots to ensure we have enough spacing to have him land, vacate the runway, and then for me to land. As it was, by the time I found the aircraft’s speed on vpilot and slowed down, it wasn’t quite enough and we had to go around. So example: User presses right bracket P and sees an aircraft. It says:AAL123, type A320, altitude 3000, IAS 200, ground speed 250.   Sent from Mail for Windows From: Andy BorkaSent: 07 September 2021 16:01To: jfayre/talking-flight-monitor-netCc: blindflightsimmer; AuthorSubject: Re: [jfayre/talking-flight-monitor-net] feature request: aircraft dialogue reads aircraft speed (#113) Can you give a case where ] S, A, H, V, and M wont work for spacing and Vatsim?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jfayre** [comment]
I can take this one. Should be very easy to add. Just need to add 
another column to the list view.

**Comment by blindflightsimmer** [comment]
<!--
/* Font Definitions */
@font-face
	{font-family:"Cambria Math";
	panose-1:2 4 5 3 5 4 6 3 2 4;}
@font-face
	{font-family:Calibri;
	panose-1:2 15 5 2 2 2 4 3 2 4;}
/* Style Definitions */
p.MsoNormal, li.MsoNormal, div.MsoNormal
	{margin:0cm;
	font-size:11.0pt;
	font-family:"Calibri",sans-serif;}
a:link, span.MsoHyperlink
	{mso-style-priority:99;
	color:blue;
	text-decoration:underline;}
.MsoChpDefault
	{mso-style-type:export-only;}
@page WordSection1
	{size:612.0pt 792.0pt;
	margin:72.0pt 72.0pt 72.0pt 72.0pt;}
div.WordSection1
	{page:WordSection1;}

**Comment by blindflightsimmer** [comment]
To add to this request, I've found the right bracket P command can be very laggy on vatsim if there are many aircraft around, for example during an event it can tak up to ten seconds for the dialogue to load and then for the user to tab and find the dialogue if it doesn't auto-focus. This is definitely not TFM's fault, just general lag due to the amounts of traffic sometimes, but to reduce it it would be much easier I think if right bracket P would just automatically read the three nearest aircraft for example through the users selected speech method. Shift P could bring up the full dialogue. This also means the user does not have to leave the simulator cockpit view on approach or departure when checking if an aircraft is ahead for example, losing focus from the sim/fms can be annoying in vital stages of flight

**Comment by ajborka** [comment]
This is fixed.
