### ISSUE TITLE
Feature Request:  Allow TFM to Read Warnings or Failures

### ISSUE THREAD

**Issue by IndomitableHeart** [jfayre/talking-flight-monitor#118]
It would be great if TFM could read the associated warning or failure display messages when there's an alarm sounding.  Last night I received an alarm sound, but had no idea of what was causing it, because the sound persisted even after clearing all failures through the PMDG menu.  I ended up having to close and reopen the simulator to silence the alarm.

**Comment by trodick** [comment]
A lot of these show up on the EICAS, and as far as I know the text from that display is not accessible via the SDK. What we need is a way to push the master caution button, as that silences the alarm. The warning is stored in the respective aircraft's WARN_annunMASTER_CAUTION offset, and can be cleared by sending the proper control events to the EVT_MASTER_CAUTION_LIGHT_LEFT and EVT_MASTER_CAUTION_LIGHT_RIGHT event IDs.

**Comment by BviPilots** [comment]
Hi,
I think this would be great as well. I know that not everyone might
have it where things can go wrong, but i actually like setting mine so
that things can happen if you dont take care of your plain. For
example, even with the oil that the engine needs. For example, if i go
and go and never service the plain, it can cause problems with the
engine for not changing the oil from time to time. I like this idea,
sounds really cool.

**Comment by ajborka** [comment]
Set a hotkey in the FMC under main menu>PMDG setup>keyboard. There should be an option for master caution/warning.

**Comment by ajborka** [comment]
This is possible with alternative methods stated above. Since we don't have access to the icas panel, it is impossible to read the error or warning the master caution/warning lights are referencing.
