### ISSUE TITLE
tfm speed not saving

### ISSUE THREAD

**Issue by BviPilots** [jfayre/talking-flight-monitor#127]
When you are flying in the freeware plains and try and update speeds in tfm, the speeds do not update for some reason. Even after setting the speed in fstramp and then going and trying to update in tfm, it will not update. Not sure if this was reported or not, but if not then hopefully it's something easy.

**Comment by ajborka** [comment]
In FSTramp, open settings, go to the flight plan tab, tab until you find the sections that deal with M1 and M2. Make sure M1 is not set to set heading and hold. Same with speed, altitude, heading, mach, and all of the others.
