### ISSUE TITLE
bug: PMDG B777: Electrical Panel: Primary and secondary ground power switches are reversed, Primary Ground Power toggles secondary and vice-versa

### ISSUE THREAD

**Issue by robin24** [jfayre/talking-flight-monitor#129]
The primary and secondary ground power switches on the PMDG B777's electrical panel are hooked up in reverse.

Consequently, toggling the Primary Ground Power switch results in Secondary ground Power being toggled and vice-versa.

**Comment by jfayre** [comment]
This has now been fixed.
