### ISSUE TITLE
bug: unable to edit speeds in the 777 cdu

### ISSUE THREAD

**Issue by marrie** [jfayre/talking-flight-monitor#131]
**Describe the bug**
When I am trying to edit speeds and alts in the 777, I cannot when entering into the scratch pad or holding tab key in the simulator.

**To Reproduce**

1. launch tfm
2. launch a flight after launching p3d
3. try and edit speeds and altitude while in the air
4. try and copy them to right soft 1-5
I should add you need to be in the legs page in order to do this.

**Expected behavior**

I used to be able to edit the speeds and altitudes in the 777.

**additional information
 - OS: [e.g. Windows 10]Windows 10 21H1 (x64) build 19043.1415
 - TFM version: Version 22.1.0.0
 - Flight simulator in use:  p3dv4
- specific aircraft in use: boeing 777 200lr house

**Additional context**

I'm running active sky and sim toolkit. here is a [link](https://www.transferxl.com/download/00vC8qrBM8mLxB) to the video. I don't say anything but basically I am writing ".88/fl390" into the scratch pad then hitting rsk1 (IE, right softkey 1).

I might have found the cause, ibid fsuipc reference in issue 132. I'm testing htis by creating a flight from scratch.

**Comment by ajborka** [comment]
This appears to be working now.
