### ISSUE TITLE
bug:  context menu says "unknown"

### ISSUE THREAD

**Issue by marrie** [jfayre/talking-flight-monitor#133]
**Describe the bug**
when invoking the context menu with the applications key or the shift  f10 key, I hear "unknown."

**To Reproduce**

1. launch tfm
2. get to the system tray with windows b.
3. hit either shift f10 or applications key. Jaws testers,  feel free to see if it says unknown for you when playing with tfm.

**Expected behavior**
I should not hear "unknown." I'm not sure what the windows default for a contextual menu is, but what ever that is, that should fire instead.

**additional information
 - OS: [e.g. Windows 10]Windows 10 21H1 (x64) build 19043.1415
 - TFM version: Version 22.1.0.0
 - Flight simulator in use: prepar3dv4.5
- specific aircraft in use: n/a

**Additional context**
n/a

**Comment by ajborka** [comment]
Does the context menu work? If so, there isn't anything we can do because it is an NVDA problem. There are times where TFM hangs because of a simulator crash where the context menu is listed as unknown, but I am unaware of any other problems with it.

**Comment by marrie** [comment]
Yeah it works, I have to down arrow to  actually get the thing to focus. I don’t know of any other app that shows “unknown” however.

Thanks.

**Comment by ajborka** [comment]
Ok, will look into it.

**Comment by marrie** [comment]
Take your time, so far for me the app has not crashed, knock on wood. I did have tfm shut down during about 80 percent of the flight though as I was not on that computer during most of said journey.

Thanks.

**Comment by ajborka** [comment]
Fixed by 466fbb3.
