### ISSUE TITLE
bug:  when closing other doors using the doors panel, I don't hear through sim connect weather the event fired.

### ISSUE THREAD

**Issue by marrie** [jfayre/talking-flight-monitor#134]
**Describe the bug**
I was playing with the doors via fs actions, then doors. I was openign and closing doors and the only one I heard  fire was "door 1 open" and "door one closed." When I pressed the other keys for the doors, I could see in the cdu they were openign and closing however simconnect did not tell me this.

**To Reproduce**
1. go to fs actions
2. hit lsk3 
3. Now start playing with the doors. Note that the only one that says the status is as far as I'm aware, door 1

**Expected behavior**
I believe I should be hearing all the doors' statuses.

**additional information
 - OS: [e.g. Windows 10] Windows 10 21H1 (x64) build 19043.1415
 - TFM version:  Version 22.1.0.0
 - Flight simulator in use:  p3dv4.5
- specific aircraft in use: pmdg 737-800 house

**Additional context**
I am running active sky, sim connect, FSUIPC  (I am not sure of the version of any of that)

Thanks.

**Comment by ajborka** [comment]
This isn't supported in 22.1.3. Only the 777 series is supported on the doors announcements.

**Comment by marrie** [comment]
Oh woops? Noted for the future.

 

Thanks.
