### ISSUE TITLE
bug: using f1 through f12

### ISSUE THREAD

**Issue by BviPilots** [jfayre/talking-flight-monitor#136]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**additional information
 - OS: [e.g. Windows 10]
 - TFM version: 
 - Flight simulator in use: 
- specific aircraft in use:

**Additional context**
Add any other context about the problem here. What other add-ons were you running at the time, etc.
With the latest update, when i try and use the f1 through f12 keys, it doesnt work for me, instead it acts like im opening a menu that might be at the top where your menu bar is located. For example i hit f8 for right soft 2 it will say something like maxamize window or something like that. Not sure what might be going on.

**Comment by ajborka** [comment]
The settings upgrade code we had previously put in to handle this problem was removed by accident. Will put it in for the next release.

**Comment by ajborka** [comment]
Fixed by 466fbb3

**Comment by ajborka** [comment]
Wrong commit number. Closed by 556cce1
