### ISSUE TITLE
bug: alternate softkeys not working in the pmdg 737

### ISSUE THREAD

**Issue by TowerAlphaTheta15** [jfayre/talking-flight-monitor#139]
**Describe the bug**
When selecting the alternate set of softkeys in the pmdg section of TFM, they don't work when you attempt to programme the FMC
**To Reproduce**

Launch TFM, go to settings, pmdg, and select the alternate softkeys option.
then close TFM, go to your simulater and press [ control c to launch the FMC
Then try pressing one of the f keys.

**Expected behavior**
I expected the option corisponding to the function key i pressed to launch
**additional information
 - OS: [e.g. Windows 10]
 - TFM version: 
 - Flight simulator in use: 
- specific aircraft in use:
OS Name: Windows 10.
TFM Version: 2204
simulator in use: Prepar3d v5
aircraft: PMDG boeing 737-600

**Additional context**
Add any other context about the problem here. What other add-ons were you running at the time, etc.
I was running Flight simulator first officer proffessional, GSX and active sky

**Comment by ajborka** [comment]
It's a known issue. A rewrite of the settings and keyboard manager systems are in progress.

**Comment by TowerAlphaTheta15** [comment]
I am just curiousIf it is a known issue why hasn’t it been fixed before nowAlso, just a minor note, when metric is enabled in the settings screen it doesn’t seem to be doing anythingThank you,Tower.  Sent from Mail for Windows From: Andy BorkaSent: 12 April 2022 19:45To: jfayre/talking-flight-monitorCc: TowerAlphaTheta15; AuthorSubject: Re: [jfayre/talking-flight-monitor] bug: alternate softkeys not working in the pmdg 737 (Issue #139) It's a known issue. A rewrite of the settings and keyboard manager systems are in progress.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by ajborka** [comment]
We work on multiple issues at a time. Thanks for your patience and understanding.
