### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by jessieppp** [jfayre/talking-flight-monitor#146]
**Describe the bug**

When switching the iru to aline mode the right light status keeps getting read out by the screen reader.
**To Reproduce**

1 open the cockpit pannel with left bracket plus p
2 navigate to the first panel, expand it with the right arrow and find iru
3 tab to the left and right dials and switch them to aline, notice how the screen reader keeps reading the on and off status of the right light.  may read the status of the left one as well but not as frequent.

**Expected behavior**

Expected to hear the light status change but not as often.
**additional information
 - OS: [e.g. Windows 10]Windows 11 21H2 (x64) build 22000.778
 - TFM version:  preview 22.7.1
 - Flight simulator in use:  p3d ver 4.5
- specific aircraft in use: pmdg b737-8ngxu

**Additional context**

n/a

**Comment by ajborka** [comment]
When the IRU switches are set to align, the IRU lights blink when the FMC is requesting the position. They will stop blinking under two conditions. (1) You fill out the initpos page with the required information, or (2) you go to TFM settings/PMDG/737 speech events/Aft Overhead/ADIRU and uncheck the boxes for left irs indicator and right irs indicator. It might help to keep up with the blog at www.talkingflightmonitor.com/blog, and the YouTube channel at https://www.youtube.com/channel/UCJy9gMmXFBZRGcC7pTY4vww
