### ISSUE TITLE
bug: warp to runways does not currently work in latest preview

### ISSUE THREAD

**Issue by marrie** [jfayre/talking-flight-monitor#154]
Issue

When warping to a runway with tfm then control r or gate with tfm then control G nothing happens, no dialogue come up wherein I can type the code.

Steps

Launch prepar

Get into a plane, does not matter which one

Hit right bracket then control R or control G

Notice the dialogues for airport and or gates and or runways does not appear.

Expected:

I expected the dialogues to appear per the blog article.

Actual:

Nothing seme dot happen. I even tried on one desktop instead of my 6 I have up.

Software

Tfm: tfm-preview-22.11 (1)

Sim: prepar3dv4.5

Plane: any plane

Other Add ons: n/a

[file example](https://user-images.githubusercontent.com/3614487/203653291-402acb49-3de1-4989-8b84-a8303892004f.mp4)

**Comment by ajborka** [comment]
When you install 22.11 preview, it overwrites the current 2.5.x release of TFM. Try using jump to gate/runway again, but use the Talking flight monitor icon on the desktop instead of the icon for the preview build. Will have to put in a fix for the installer.

**Comment by marrie** [comment]
Sadly, that did not work. I still get the airspeed hold and if I hit my tfm keys, any of them they work, except ath one, which means the key is not intersepted.

**Comment by ajborka** [comment]
First, TFM has nothing to do with airspeed being too fast/slow. When I downloaded the preview build, it installed over top of my official 22.5 release. Either way, the 22.11 preview works with the jump to options.

**Comment by marrie** [comment]
Yeah, that particular key stroke is not being intercepted by tfm when right bracket is pressed. I just had someone else try and they could not get it to work either. Something is blocking these two keystrokes and thereby preventing tfm from executing said actions. I’ve already tried in the f18 and in the pmdg, results are the same.

**Comment by ajborka** [comment]
Follow these steps.

•	Download the current preview from [www.talkingflightmonitor.com/preview-releases](http://www.talkingflightmonitor.com/preview-releases).
•	Uninstall the existing TFM installation.
•	Reinstall TFM from the download in step 1.
•	Load P3D, FSX, or msfs.
•	Load an airplane of choice.
•	When in the cockpit (after the airplane loads), start TFM by clicking on the “Talking flight monitor” icon on the desktop.
•	After TFM loads, press right bracket (]), then CTRL+R or CTRL+G to activate the jump to… feature.
Make sure you run makerunways before using jump to… It made no difference when opening the dialogs though. Aside from this, make sure antivirus apps aren’t blocking TFM, or quarantining it.

**Comment by marrie** [comment]
Got it, yep, just as a note, it did in fact  overwrite the location that looks like it is the default. woops? Now I need to reset up my stuff, that's fine.
