### ISSUE TITLE
braille support.

### ISSUE THREAD

**Issue by stickbear2015** [jfayre/talking-flight-monitor#24]
As we continue this awesome development, would it be possible to intigrate braille support so that output from command keys like c d, etc. are outputted to a braille display if one is present and seen by NVDA?

**Comment by ajborka** [comment]
Yes... It might take some time though. There are quite a few places where speech is outputted, so we would need to go through and add the braille support.

**Comment by jfayre** [comment]
In reading the Tolk documentation, it looks like it should send output to Braille displays with the default Output function. I will test this later tonight.

**Comment by jfayre** [comment]
I verified that the default Tolk output function sends text to a braille display as well as speaking the text, Closing this issue.

**Comment by stickbear2015** [comment]
Jason,
sorry, but I'm re-opening this issue because the default output at least on smaller displays (braille note apex), when things are outputted you can't scroll back to read the beginning of the output, from commands like W.
SO while the default does output, it doesn't output in a way that's actually useful especially when your only getting some of the output and your reliant on braille, for whatever the reason.
I have yet to see if this output bug is also a thing on larger displays.
note: this is not a screen reader related issue.

**Comment by jfayre** [comment]
Hmm. Ok. The only way to resolve this would be to send different text to the display than we are sending to speech. I would say that is a much bigger job. 

Tolk sends text to the display as status messages, so they clear after a few seconds. The clearing of the message is done by the screen reader. I’m not sure we have any control over that without coding directly to individual screen reader APIs.

**Comment by stickbear2015** [comment]
I know it's doable as I've seen it done I've got current source for tfm, I'll see if I can find toke's source.
It may also get better once the speech output read only edit gets populated and we can jump in their and scroll to our hearts content.
Their are options, it's just finding the one that makes the most sense.

**Comment by ajborka** [comment]
Don't override the default screen reader behavior... It's bad programming practice. After all, the screen reader controls the output generated by the software, not the other way around. If tolk outputs braille as status messages, set the screen reader to constantly display status messages until dismissed by the user. JAWS and NVDA allow configuration profiles in which you can have completely different sets of settings based on the application opened with focus at the time. Most braille displays should have a setting for that as well. In either case, I am reworking the speech system to include braille, speech, or both. The benefit is that speech output might look/sound different than braille. EX: braille messages can be shorter than speech output, or the level of detail a message [speech/braille] will eventually be controlled independently from each other.

**Comment by ajborka** [comment]
Fixed
