### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by armstrong25** [jfayre/talking-flight-monitor#60]
I would like to see tfm when going to lock on to a locallizer announce the heading of the locallizer your trying to lock on to.  for example, if you have a runway with a heading of 350, then tfm should announce something like locallizer is alive n1 set to 350, that way you know your locking onto the right locallizer to land the aircraft.

**Comment by jfayre** [comment]
I’m fairly sure this is possible. I assume this is the Nav 1 Course reading we are looking for at that point?

**Comment by armstrong25** [comment]
Yes

**Comment by ajborka** [comment]
Fixed by 5c636dc.
