### ISSUE TITLE
TFM bounces the aircraft when using takeoff assist.

### ISSUE THREAD

**Issue by armstrong25** [jfayre/talking-flight-monitor#88]
when hitting right bracket control a the aircraft still moves.  when hitting toga while the aircaft is moving when it lifts off it stalls out and bounces.

**Comment by ajborka** [comment]
The aircraft moving upon touchdown when it is initially placed on the runway has nothing to do with TFM. The runway might be on a hill, or the scenario setup for that aircraft might have the parking break turned off. TFM bouncing the plane is another story, and we are looking into it. This will take some time though.

**Comment by ajborka** [comment]
The current version of takeoff assist will be removed in a future update.
